2020-05-10 13:22:08,707 ERROR: Exception on /about [GET] [in /home/user/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 333, in about
    return render_template('about.html', title = 'About')
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Documents/Scripts/microblog/app/templates/about.html", line 106, in template
    {% endblock %}
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2020-05-10 13:22:33,061 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:23:37,722 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:23:57,838 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:24:07,745 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:24:21,515 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:24:41,179 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:25:55,793 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:26:37,581 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:27:16,670 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:28:02,123 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:29:38,164 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:32:54,463 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:48:16,510 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-10 13:48:17,368 ERROR: Exception on /about [GET] [in /home/user/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 333, in about
    return render_template('about.html', title = 'About')
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Documents/Scripts/microblog/app/templates/about.html", line 4, in top-level template code
    {% block head %}
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/user/Documents/Scripts/microblog/app/templates/about.html", line 11, in root
    {{ bootstrap.load_css() }}
  File "/home/user/Documents/Scripts/microblog/app/templates/about.html", line 24, in block_head
    <!-- Optional JavaScript -->
  File "/home/user/Documents/Scripts/microblog/app/templates/about.html", line 34, in block_styles
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'bootstrap' is undefined
