2020-01-08 11:25:34,837 ERROR: Exception on /monitoring [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 106, in monitoring
    x.append(record.cpu_usage).timestamp()
AttributeError: 'NoneType' object has no attribute 'timestamp'
2020-01-08 11:26:06,832 ERROR: Exception on /monitoring [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 106, in monitoring
    x.append(record.cpu_usage).timestamp()
AttributeError: 'NoneType' object has no attribute 'timestamp'
2020-01-08 11:28:46,892 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-08 11:28:50,258 ERROR: Exception on /monitoring [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 109, in monitoring
    y= matplotlib.matplotlib_fname().dates.date2num(y)
AttributeError: 'str' object has no attribute 'dates'
2020-01-08 11:30:44,524 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-08 11:30:46,549 ERROR: Exception on /monitoring [GET] [in /usr/lib/python3/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 109, in monitoring
    y = matplotlib.matplotlib_fname().dates.date2num(y)
AttributeError: 'str' object has no attribute 'dates'
2020-01-08 11:31:44,658 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-08 12:02:07,297 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-08 12:02:22,356 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-17 02:17:31,366 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-17 02:23:45,738 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 04:58:44,094 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 05:01:07,371 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 05:04:08,185 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 05:05:17,005 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:10:10,487 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:10:42,593 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:15:12,635 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:16:11,369 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:29:42,369 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:30:21,764 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:33:34,736 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:42:48,801 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
2020-04-27 14:45:51,009 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:43]
