2020-05-12 17:01:15,658 ERROR: Exception on /user/Administrator [GET] [in /home/user/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 97, in user
    return render_template('user.html', user=user, systems=uniqueList,posts=posts )
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/user/.local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Documents/Scripts/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/user/Documents/Scripts/microblog/app/templates/user.html", line 14, in root
    </td>
  File "/home/user/Documents/Scripts/microblog/app/templates/base.html", line 14, in root
    <li class="nav-item oo-roboto-override dropdown">
  File "/home/user/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/user/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/user/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/user/.local/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/home/user/Documents/Scripts/microblog/app/templates/base.html", line 84, in block_content
  File "/home/user/Documents/Scripts/microblog/app/templates/user.html", line 51, in block_app_content
  File "/home/user/Documents/Scripts/microblog/app/templates/_post.html", line 12, in root
  File "/home/user/.local/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2020-05-12 17:01:55,989 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:02:36,508 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:04:01,958 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:06:28,047 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:08:22,777 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:08:58,881 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:09:12,703 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:09:30,243 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:10:20,655 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:10:53,736 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:13:31,497 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:13:32,525 ERROR: Exception on /user/Administrator [GET] [in /home/user/.local/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/user/Documents/Scripts/microblog/app/routes.py", line 90, in user
    time_added =session.query(System.timestamp).order_by(+System.timestamp).first()
TypeError: bad operand type for unary +: 'InstrumentedAttribute'
2020-05-12 17:14:41,943 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
2020-05-12 17:15:29,179 INFO: Microblog startup [in /home/user/Documents/Scripts/microblog/app/__init__.py:46]
